<!doctype html>
<html lang="es">
    <head>
        <title>Portal</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
     
    <?php
    //if ($this->ckeditor){
        echo $this->headScript()->appendFile( $this->baseUrl().'/js/ckeditor/ckeditor.js');
     //}
    ?>    
        
    <link href="/css/styles.css" rel="stylesheet" type="text/css">
    </head>
    
    <body>
        
        <header>   
            <hgroup>
                <a href="/posts/agregar/" >Agregar Post</a>
                <h1>News Programación</h1>
            </hgroup>
        </header>
        
        <nav>
            <ul>
                <li><a href="/">Home  |</a></li>
                <li><a href="categorias/web/">Web & Diseño   |</a></li>
                <li><a href="categorias/software/">Sofware & App   |</a></li>
                
            </ul>
        </nav>
        
        <section>
            <?php echo $this->layout()->content; ?>
        </section>
        <footer>
            Opcion1 | Opcion2 | Opcion3 | Opcion4
        </footer>
    </body>
</html>

