<!doctype html>
<html lang="es">
    <head>
        <title>Portal</title>
        <meta charset="utf-8">
     
    <link href="../public/css/styles.css" rel="stylesheet" type="text/css">
    </head>
    
    <body>
        <header>
            <hgroup>
                <h1>News Programación</h1>
            </hgroup>
        </header>
        
        <nav>
            <ul>
                <li><a href="/">Home  |</a></li>
                <li><a href="/">Web & Diseño   |</a></li>
                <li><a href="/">Sofware & App   |</a></li>
                
            </ul>
        </nav>
        
        <section>
            <?php echo $this->layout()->content; ?>
        </section>
        <footer>
            Opcion1 | Opcion2 | Opcion3 | Opcion4
        </footer>
    </body>
</html>

